### ISSUE TITLE
Installation issue on Ubuntu

### ISSUE THREAD

**Issue by kiranbayram** [rtimush/tenpureto#10]
Hello there,

I was trying to build from source code on my Ubuntu (Ubuntu 18.04.2 LTS
) and got the error below. I should probably install some library to fix it but wanted to open an issue, so that we address this in documentation.

```
* Missing (or bad) C libraries: icuuc, icui18n, icudata
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
the library files do exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

**Comment by rtimush** [comment]
I think the missing package is `libicu-dev`, I will add a note to the readme.

**Comment by kiranbayram** [comment]
Thanks, i'll try installing it later again.

**Comment by kiranbayram** [comment]
Installation succeeded after installing `libicu-dev` but tenpureto command was still not available in the terminal(even after opening a new terminal). Do i need to do more configuration for this ?

**Comment by rtimush** [comment]
You can either use it as `stack run -- <options here>`, or you can run `stack install` and add `~/.local/bin` to your path. Hope this helps.
I also plan to start building native packages soon, so it will be easier to install on Linux.

**Comment by kiranbayram** [comment]
Yes, that worked. Thanks :)

**Comment by rtimush** [comment]
Added some additional info to the readme in 20f349ba8a6734e34ecd123f85e7a654bdeb8734
