### ISSUE TITLE
Allow the use of offline (that is, locally-stored) templates

### ISSUE THREAD

**Issue by kozross** [rtimush/tenpureto#6]
Having to call out to an online repo every time I want to create a project from a template is overly onerous. However, based on the documentation you have so far, it seems that's the only choice.

**Comment by rtimush** [comment]
It's totally possible to use it with a local template by passing a path as an argument:
```bash
$ tenpureto create --template /path/to/the/local/template my-project
```
It should also work with a mirror clone of an online repo, but won't work with a regular clone.

**Comment by kozross** [comment]
@rtimush Thanks for responding! Your README should definitely say this, then. I'm happy to make a PR to that effect if you like.

**Comment by rtimush** [comment]
Yes, a readme note would be nice, will be happy to accept a PR if you make one! And sorry for a late answer — I didn't expect anyone to find the project at such an early stage, so missed the issues you had created.
